name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git \
            --depth 1 --branch 3.27.4 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Flutter doctor
        run: flutter doctor

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze --no-fatal-infos

      - name: Build APK debug
        run: |
          flutter build apk --debug \
            --split-per-abi \
            --build-number=${{ github.run_number }}

      - name: Upload APK debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-arm64-v8a-debug.apk
          retention-days: 7
